### ISSUE TITLE
@loader Issues

### ISSUE THREAD

**Issue by J-Mo63** [amberframework/granite#258]
## Issue
I'm working on building out an API for myself and I'm currently trying to add persistence, however I get the following error from even a simple `Example.all`.
```crystal
in lib/granite/src/granite/collection.cr:4: instance variable '@loader' of Granite::Collection(Example) must be Proc(Array(Example)), not Proc(Array(Example))

  def initialize(@loader : -> Array(M))
```
I looked over issue #244 the other day in search of answers and the workaround provided isn't quite enough for my purposes (plus it looks a little hacky). There seems to be no documentation for the syntax described in the issue, and all I really want to do here is to call `.all`, `.find`, `.create`, and `.update`. I don't have many dependencies for it to be clashing with unlike the other poster, and I'm not trying to do anything all that complex at this point.

So my question:
1) Is there potential for this to be fixed in a release in the near future, and if not;
2) Is there more comprehensive documentation on this other syntax?

## Additional Code for Reference

**shards.lock**
```yml
version: 1.0
shards:
  db:
    github: crystal-lang/crystal-db
    version: 0.5.0

  granite:
    github: amberframework/granite
    version: 0.12.1

  inflector:
    github: phoffer/inflector.cr
    version: 0.1.8

  mime-types:
    github: jwaldrip/mime-types-cr
    version: 1.3.0

  oak:
    github: obsidian/oak
    version: 2.0.1

  orion:
    github: obsidian/orion
    version: 1.5.0

  pg:
    github: will/crystal-pg
    version: 0.15.0
```

**all my requirements**
```crystal
# Library Requirements
require "orion"
require "json"
require "granite/adapter/pg"
```

**calling my helper**
```crystal
# Includes
include Frost::ModelHelper

# Migrate DB
initialise_tables [User, Example]
```

**model helper**
```crystal
module Frost::ModelHelper
  def initialise_tables(models : Array(Granite::Base.class))
    puts "Initialising tables..."
    tables_existed = 0
    models.each do |model|
      begin
        model.migrator.create
        puts "#{model} table created"
      rescue
        tables_existed += 1
      end
    end
    created = models.size - tables_existed
    puts "#{created} new #{pluralize("table", created)} created of #{models.size} #{pluralize("model", models.size)}"
  end

  def pluralize(singular : String, value : Int32)
    value == 1 ? singular : singular + 's'
  end
end
```

**my user model**
```crystal
class User < Granite::Base
  extend Granite::Query::BuilderMethods
  adapter pg

  # Fields
  timestamps
  primary id : Int64
  field first_name : String
  field last_name : String
  field email : String
  field password_hash : String

  # Object methods
  def full_name
    "#{first_name} #{last_name}"
  end
end
```

**my example model**
```crystal
class Example < Granite::Base
  extend Granite::Query::BuilderMethods

  adapter pg

  # Fields
  timestamps
  primary id : Int64
  field name : String
  field body : String

  # Object methods
end
```

**the api method calling it**
```crystal
def index
    Example.create(name: "Test", body: "Data")
    respond Example.all
end
```

**the full error (up to relevant trace)**
```crystal
instantiating 'ExampleApi#index()'
in src/api/example_api.cr:6: instantiating 'Example:Class#all()'

    respond Example.all
                    ^~~

in lib/granite/src/granite/querying.cr:52: instantiating 'all(String, Array(Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil))'

  def all(clause = "", params = [] of DB::Any)
  ^

in lib/granite/src/granite/querying.cr:53: instantiating 'Granite::Collection(Example):Class#new(Proc(Array(Example)))'

    Collection(self).new(->{ raw_all(clause, params) })
                     ^~~

in lib/granite/src/granite/collection.cr:4: instance variable '@loader' of Granite::Collection(Example) must be Proc(Array(Example)), not Proc(Array(Example))

  def initialize(@loader : -> Array(M))
                 ^~~~~~~
```
