### ISSUE TITLE
Are the adapters docs right?

### ISSUE THREAD

**Issue by shayneoneill** [amberframework/granite#263]
I have this code
```
require "granite"
require "granite/adapter/pg"
Granite::Adapters << Granite::Adapter::Pg.new({name: "pg", url:<url snipped>})
```

It produces this error;-
```

in src/lib/database.cr:4: undefined constant Granite::Adapters (did you mean 'Granite::Adapter')

Granite::Adapters << Granite::Adapter::Pg.new({name: "pg", url: "SNIP"})
^~~~~~~~~~~~~~~~~
```

Cant work out what I'm doing wrong here, Im using the latest github main branch as per docs, but I cant even find "Adapters" in a grep of the library.

Where these docs committed before the actual code?

From specs
```
dependencies:
  pg:
    github: will/crystal-pg
    version: "~> 0.5"
  granite:
    github: amberframework/granite
  micrate:
    github: juanedi/micrate
```
