### ISSUE TITLE
New 0.17.3 shards bug

### ISSUE THREAD

**Issue by OrelSokolov** [amberframework/granite#364]
This config was good for yesterday, but today this config
```
  amber:
    main: lib/amber/src/amber/cli.cr

dependencies:
  amber:
    github: amberframework/amber
    version: 0.30.0
    #branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.17.0

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.5.3

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.2.4

  pg:
    github: will/crystal-pg
    version: ~> 0.18.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: 0.4.0

development_dependencies:
  garnet_spec:
    github: amberframework/garnet-spec
    version: 0.2.1

```

produces
```
Fetching https://github.com/amberframework/granite.git
Error resolving db (*, ~> 0.6.0, ~> 0.6.0, ~> 0.6.0, ~> 0.7.0)
```
