### ISSUE TITLE
Running Amber Watch triggers a Granite bug

### ISSUE THREAD

**Issue by nsuchy** [amberframework/granite#365]
Running amber in Crystal 0.30.1 encounters a Granite bug. Information is as follows.

**Error output:**
```
╰─$ amber watch
07:54:31 Watch run  | (INFO) Building...
Showing last frame. Use --error-trace for full trace.

In lib/granite/src/adapter/base.cr:52:12

 52 | db.query statement, args: params do |rs|
         ^----
Error: no overload matches 'DB::Database#query' with types String, args: (Int32 | Nil)

Overloads are:
 - DB::QueryMethods(Stmt)#query(query, *args_, args : Array | ::Nil = nil)
 - DB::QueryMethods(Stmt)#query(query, *args_, args : Array | ::Nil = nil, &block)
07:54:33 Watch run  | (INFO) Compile time errors detected, exiting...
```

**My shards.yml file:**
```
name: ulayer
version: 0.1.0

authors:
  - Nathaniel Suchy <me@lunorian.is>

crystal: 0.30.1

license: UNLICENSED

targets:
  ulayer:
    main: src/ulayer.cr

  amber:
    main: lib/amber/src/amber/cli.cr

dependencies:
  # amber:
  #   github: amberframework/amber
  #   version: ~> 0.30.1
  amber:
    github: bcardiff/amber
    branch: crystal/0.31.0

  granite:
    github: amberframework/granite
    version: ~> 0.17.3

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.5.3

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.2.5

  pg:
    github: will/crystal-pg
    version: ~> 0.19.0

  mysql:
    github: crystal-lang/crystal-mysql
    version: ~> 0.9.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: ~> 0.4.0

  crylog:
    github: Blacksmoke16/crylog

  CrystalProxmox:
    github: ulayer/CrystalProxmox
```

**My shards.lock file**
```
version: 1.0
shards:
  CrystalProxmox:
    github: ulayer/CrystalProxmox
    commit: 79d026f2bf579ead3974b10efaa511db8caa08fd

  amber:
    github: bcardiff/amber
    commit: d6dce70e2996e26d34ecb2099ec0c8bf6af104dc

  amber_router:
    github: amberframework/amber-router
    version: 0.3.0

  callback:
    github: drujensen/callback
    version: 0.7.1

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: 0.4.0

  cli:
    github: drujensen/cli
    version: 0.8.0

  compiled_license:
    github: elorest/compiled_license
    version: 0.1.3

  crylog:
    github: Blacksmoke16/crylog
    version: 0.1.2

  db:
    github: crystal-lang/crystal-db
    version: 0.7.0

  email:
    github: arcage/crystal-email
    version: 0.3.3

  exception_page:
    github: crystal-loot/exception_page
    version: 0.1.2

  granite:
    github: amberframework/granite
    version: 0.17.3

  i18n:
    github: TechMagister/i18n.cr
    version: 0.3.1

  inflector:
    github: phoffer/inflector.cr
    version: 0.1.8

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: 0.2.5

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  liquid:
    github: TechMagister/liquid.cr
    version: 0.3.1

  markd:
    github: icyleaf/markd
    version: 0.1.2

  micrate:
    github: amberframework/micrate
    version: 0.3.4

  mysql:
    github: crystal-lang/crystal-mysql
    version: 0.9.0

  optarg:
    github: drujensen/optarg
    version: 0.7.0

  pg:
    github: will/crystal-pg
    version: 0.19.0

  pool:
    github: ysbaddaden/pool
    version: 0.2.3

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: 0.5.3

  redis:
    github: stefanwille/crystal-redis
    version: 2.2.1

  shell-table:
    github: luckyframework/shell-table.cr
    commit: 078a04ea58ead5203bb435a3b5fff448ddabaeea

  slang:
    github: jeromegn/slang
    version: 1.7.1

  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: 0.14.0

  string_inflection:
    github: mosop/string_inflection
    version: 0.2.1

  teeplate:
    github: mosop/teeplate
    version: 0.8.0
```
