### ISSUE TITLE
Update to crystal-db ~> 0.8.0

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite#376]
Any plans to do this? I am currently running crystal 0.32.0 and granite is broken for me.

Thanks

**Comment by Blacksmoke16** [comment]
Oh, yea I can take care of this tonight.

**Comment by Blacksmoke16** [comment]
@lebogan, what issue exactly are you running into? Specs pass fine in `0.32.1` with current dependencies.

Obviously I'll update them and CI anyway but it's likely that isn't the root of your problem.

**Comment by lebogan** [comment]
Running `shards install` on a new project yields this error:
```
Error resolving db (~> 0.8.0, ~> 0.8.0, ~> 0.8.0, ~> 0.7.0)
```
Shards 0.8.1 [0147a56] (2019-12-18)
Crystal 0.32.1 [41bd18fbe] (2019-12-18)


My shard.yml:
```
development_dependencies:
  ameba:
    github: veelenga/ameba
  micrate:
    github: amberframework/micrate

dependencies:
  pg:
    github: will/crystal-pg
  sqlite3:
    github: crystal-lang/crystal-sqlite3
  mysql:
    github: crystal-lang/crystal-mysql
  granite:
    github: amberframework/granite
```
Not sure how to resolve the error and load granite.

Thanks

**Comment by Blacksmoke16** [comment]
You need to specify versions or commit hashes for your dependencies.  If you don't then it'll use the latest version, which are using `crystal-db 0.8.0`, however Granite is pinned to `0.7.0`.  

```yaml
  mysql:
    github: crystal-lang/crystal-mysql
    version: ~> 0.9.0
  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: ~> 0.14.0
  pg:
    github: will/crystal-pg
    version: ~> 0.19.0
```

So in this case updating Granite _will_ fix this problem, but the issue itself is not a Granite issue.
